// 2ea46e48ba00a3e6d1fea5582a3eee61
// autogenerated file
#pragma once

#include <fbt/ifunction-block-fabric.hpp>

class AMOTOR_Fabric : public IFunctionalBlockFabric {
public:
    virtual std::vector<ParameterInfo> GetParametersInfo() const;
    virtual TechDataInfo GetRetainInfo() const;
    virtual FunctionBlockInfo GetFbInfo() const;
    virtual std::unique_ptr<IFunctionBlock> CreateBlock(IFunctionalBlockData& data);
};
