// autogenerated file
#include <fbt/ifunction-block-fabric.hpp>
#include "amotor/amotor-fabric.h"

static AMOTOR_Fabric varAMOTOR_Fabric;

static IFunctionalBlockFabric* fabrics[] = {
    &varAMOTOR_Fabric,
    nullptr
};

extern "C" {
    IFunctionalBlockFabric** GetFabrics() {
        return fabrics;
    }
}
